name: Actions workflow
on: [push, pull_request]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Fiels
        run: |
          pwd
          ls -a
          ls -altr
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"

      - name: Checkout
        uses: actions/Checkout@v2.3.4

      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: john
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
