name: Actions workflow
on: 
  
  schedule:
    - cron: '0/5 * * * *'
 
jobs:
  run-task-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          date
          ls -a
          ls -altr
          df -h
